### PR TITLE
CI: migrate to GitHub Actions (v2)

### PR DESCRIPTION
**Pull request by lzaoral**
In general a copy-paste of https://github.com/csutils/csdiff/pull/43.

### CODE REVIEW

**Comment by kdudka** [comment]
Do we need `clang++` and `g++` for a C-only project?  Also the sanitizers should be added to `$CFLAGS` rather than `$CXXFLAGS`.

**Comment by lzaoral** [comment]
Good catch!  That serves me right for copy-pasting stuff around.

**Review by kdudka — APPROVED** [review]
Looks perfect.  Thanks!

**Comment by lzaoral** [comment]
Thanks for the review, @kdudka! Merging.

**Pull request merged**
